<?php

namespace Cradle\OAuth;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:10:59.
 */
class Cradle_OAuth2_Test extends TestCase
{
    /**
     * @var OAuth2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $clientId = '12345';
        $clientSecret = 'clientSecret';
        $url = 'http://www.googleapis.com/oauth2/v3/token';

        $this->object = new OAuth2(
            $clientId,
            $clientSecret,
            $url,
            $url,
            $url,
            $url
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\OAuth\OAuth2::getAccessTokens
     */
    public function testGetAccessTokens()
    {
        $response = $this
            ->object
            ->getAccessTokens('code');

        $this->assertNotEmpty($response);
    }

    /**
     * @covers Cradle\OAuth\OAuth2::getLoginUrl
     */
    public function testGetLoginUrl()
    {
        $clientId = '12345';
        $url = 'http://www.googleapis.com/oauth2/v3/token';
        $encodedUrl = urlencode($url);

        $response = $this
            ->object
            ->getLoginUrl();

        $this->assertEquals($url . '?response_type=code' .
                '&client_id=' . $clientId .
                '&redirect_uri=' . $encodedUrl .
                '&access_type=online' .
                '&approval_prompt=auto', $response);
    }
}
