<?php

namespace Cradle\OAuth;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:10:59.
 */
class Cradle_OAuth1_Test extends TestCase
{
    /**
     * @var OAuth1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $consumerKey = '12345';
        $consumerSecret = '67890';
        $url = 'http://www.googleapis.com';

        $this->object = new OAuth1(
            $consumerKey,
            $consumerSecret,
            $url,
            $url,
            $url,
            $url
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\OAuth\OAuth2::getAccessTokens
     */
    public function testGetAccessTokens()
    {
        $responseToken = 'token';
        $requestSecret = 'secret';
        $verifier = 'verifier';

        $response = $this
            ->object
            ->getAccessTokens($responseToken, $requestSecret, $verifier);

        $this->assertNotEmpty($response);
    }

    /**
     * @covers Cradle\OAuth\OAuth1::getLoginUrl
     */
    public function testGetLoginUrl()
    {
        $requestToken = '12345';
        $url = 'http://www.googleapis.com';
        $encodedUrl = urlencode($url);

        $response = $this
            ->object
            ->getLoginUrl($requestToken);

        $this->assertEquals($url . '?oauth_token=' . $requestToken .
                '&oauth_callback=' . $encodedUrl .
                '&force_login=0', $response);
    }

    /**
     * @covers Cradle\OAuth\OAuth1::getRequestTokens
     */
    public function testGetRequestTokens()
    {
        $response = $this
            ->object
            ->getRequestTokens();

        var_dump($response);
    }
}
