<?php

namespace Cradle\IO\Middleware;

use PHPUnit\Framework\TestCase;
use Cradle\IO\Middleware;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_IO_PreProcessorTrait_Test extends TestCase
{
  /**
   * @var PreProcessorTrait
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new PreProcessorTraitStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * covers Cradle\IO\PreProcessorTrait::getPreprocessor
   */
  public function testGetPreprocessor()
  {
    $instance = $this->object->getPreprocessor();
    $this->assertInstanceOf('Cradle\IO\Middleware', $instance);
  }

  /**
   * covers Cradle\IO\PreProcessorTrait::preprocess
   */
  public function testPreprocess()
  {
    $instance = $this->object->preprocess(function() {});
    $this->assertInstanceOf('Cradle\IO\Middleware\PreProcessorTraitStub', $instance);
  }

  /**
   * covers Cradle\IO\PreProcessorTrait::setPreprocessor
   */
  public function testSetPreprocessor()
  {
    $instance = $this->object->setPreprocessor(new Middleware);
    $this->assertInstanceOf('Cradle\IO\Middleware\PreProcessorTraitStub', $instance);
  }
}

if(!class_exists('Cradle\IO\PreProcessorTraitStub')) {
  class PreProcessorTraitStub
  {
    use PreProcessorTrait;
  }
}
